version: '3.1'

services:

  mongo:
    image: mongo
    container_name: lets-stock-backend-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./localMongoDB:/data/db

  # backend:
  #   image: lets-stock-backend-image
  #   container_name: lets-stock-backend-service
  #   restart: always
  #   ports:
  #     - 3030:3030
  #   depends_on:
  #     - mongo
